# Generated by Django 3.0.4 on 2020-04-09 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('dev_sn', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='设备SN')),
                ('name', models.CharField(max_length=50, verbose_name='设备名称')),
                ('site', models.CharField(max_length=100, verbose_name='设备安装地址')),
                ('note', models.CharField(max_length=200, verbose_name='设备的描述')),
                ('status', models.IntegerField(choices=[(0, '下线'), (1, '上线'), (2, '失效')], default=1, verbose_name='设备的状态')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='设备更新时间')),
                ('user', models.IntegerField(verbose_name='添加的用户')),
            ],
            options={
                'verbose_name': '设备配置表',
                'verbose_name_plural': '设备配置表',
                'db_table': 'ods_device',
            },
        ),
        migrations.CreateModel(
            name='DeviceLogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_created=True, verbose_name='创建时间')),
                ('get_msg', models.CharField(max_length=255, verbose_name='接收到的信息')),
                ('res_msg', models.CharField(max_length=255, verbose_name='返回的信息')),
            ],
            options={
                'verbose_name': '日志表',
                'verbose_name_plural': '日志表',
                'db_table': 'ods_dev_log',
            },
        ),
        migrations.CreateModel(
            name='DeviceStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.IntegerField(verbose_name='标志位 16进制转为10进制')),
                ('version', models.IntegerField(verbose_name='设备的版本 16进制转为10进制')),
                ('dev_sn', models.CharField(max_length=50, verbose_name='设备的SN 16进制转为10进制')),
                ('ir_voltage', models.IntegerField(verbose_name='发射设备的电量')),
                ('voltage', models.IntegerField(verbose_name='接受设备的电量')),
                ('get_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '设备状态表',
                'verbose_name_plural': '设备状态表',
                'db_table': 'ods_cache_status',
            },
        ),
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_time', models.DateTimeField()),
                ('focus', models.IntegerField(verbose_name='失焦状态')),
                ('din', models.IntegerField(verbose_name='进入')),
                ('dout', models.IntegerField(verbose_name='离开')),
                ('get_time', models.DateTimeField(verbose_name='获取数据的时间')),
                ('status', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='idtkapp.DeviceStatus')),
            ],
            options={
                'verbose_name': '设备数据表',
                'verbose_name_plural': '设备数据表',
                'db_table': 'ods_cache_data',
            },
        ),
    ]
